name: looser_spend_manager
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.7.0
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  firebase_analytics: ^10.4.4
  flutter_hooks: ^0.18.6
  flutterfire_json_converters: ^0.0.5 
  hooks_riverpod: ^2.3.6
  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.2.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
